[package]
name = "init-vuln-db"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.7", features = ["runtime-tokio-native-tls", "postgres"] }
argon2 = "0.5"
dotenv = "0.15"
